name: ESPHome Build & Release

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build & Release Firmware
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build firmware with ESPHome
        id: esphome-build
        uses: esphome/build-action@v8.1.0
        with:
          yaml-file: pocket-assistant-1.75c.yaml

      - name: Upload Binaries to GitHub Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ steps.esphome-build.outputs.name }}/*.bin
            ${{ steps.esphome-build.outputs.name }}/manifest.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
